// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
